### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by halfdan** [pushbots/Instapush-php#2]
The code of this library is a mess. It should at least adhere to the PSR standards and have a consistent naming scheme. The indentation is messed up and the comments don't match up with the code.

The service is much appreciated, but having this as official library on the website doesn't make it look very good.

**Comment by pushbots** [comment]
https://github.com/pushbots/Instapush-php/commit/1403194c3e6ab3670704ca26c4890c998806d3ed
